name: Continuous Integration

on:
  pull_request:
    branches: ['master']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm run test-unit
      - name: Run E2E tests
        uses: cypress-io/github-action@v5.0.5 # use the explicit version number
        with:
          start: npm start
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
