name: Continuous Integration

on:
  pull_request:
    branches: ['master']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
      - name: Build
        run: npm run build
